// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2kqZnH1tvg3DjYBTCrQqMywZGldrwx9o',
    appId: '1:365824957626:web:ba75182be03463645ef683',
    messagingSenderId: '365824957626',
    projectId: 'e-commerce-app-5d102',
    authDomain: 'e-commerce-app-5d102.firebaseapp.com',
    storageBucket: 'e-commerce-app-5d102.firebasestorage.app',
    measurementId: 'G-MNGFZGV4FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOUf5KDjf1XIbPgJT4fLEgR-GDY_O-Uyc',
    appId: '1:365824957626:android:97474e6c30e97b665ef683',
    messagingSenderId: '365824957626',
    projectId: 'e-commerce-app-5d102',
    storageBucket: 'e-commerce-app-5d102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCithOPeBYMLN_cfXCh8WjZZopTFwbQzEI',
    appId: '1:365824957626:ios:dca39e3f970d10cf5ef683',
    messagingSenderId: '365824957626',
    projectId: 'e-commerce-app-5d102',
    storageBucket: 'e-commerce-app-5d102.firebasestorage.app',
    iosBundleId: 'com.example.eCoomerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCithOPeBYMLN_cfXCh8WjZZopTFwbQzEI',
    appId: '1:365824957626:ios:dca39e3f970d10cf5ef683',
    messagingSenderId: '365824957626',
    projectId: 'e-commerce-app-5d102',
    storageBucket: 'e-commerce-app-5d102.firebasestorage.app',
    iosBundleId: 'com.example.eCoomerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2kqZnH1tvg3DjYBTCrQqMywZGldrwx9o',
    appId: '1:365824957626:web:71e6dd916c6411895ef683',
    messagingSenderId: '365824957626',
    projectId: 'e-commerce-app-5d102',
    authDomain: 'e-commerce-app-5d102.firebaseapp.com',
    storageBucket: 'e-commerce-app-5d102.firebasestorage.app',
    measurementId: 'G-8T4G263MBT',
  );
}
